Add flag to rnp_import_keys() which allows iterative key import.
rnpgp/rnp pull request #1317
Opened 2020-09-25 11:47 UTC by ni4

This PR:
- adds flag RNP_LOAD_SAVE_SINGLE, which will just load the first key from rnp_input_t
- makes use of this flag in CLI for better user experience (so progress is displayed during key load)
- adds corresponding tests.

2020-09-26 10:44 UTC, antonsviridenko approved these changes

2020-09-27 08:12 UTC, rrrooommmaaa requested changes
Please have a look at my remarks

2020-09-28 12:16 UTC, ni4 commented on src/librekey/key_store_pgp.cpp
> +    if (key.key.tag != PGP_PKT_RESERVED) {
This approach could give us a problem in (rather theoretical) case when in future 0 packet tag will get some meaning in the protocol, and we'll be forced to change default key packet tag value to something else.

2020-09-28 12:29 UTC, ni4 commented on src/librekey/key_store_pgp.h
> +rnp_result_t rnp_key_store_pgp_read_from_src(rnp_key_store_t *keyring,
Ok, sure.

2020-09-28 12:29 UTC, ni4 commented on src/librepgp/stream-key.cpp
> +                key.subkeys.emplace_back(std::move(subkey));
Agree, thanks. Wrote that code before the discussion took place.

2020-09-28 12:37 UTC, ni4 commented
@rrrooommmaaa Fixed all except checking for zero tag, let's discuss it further here: https://github.com/rnpgp/rnp/pull/1317#discussion_r495893588

2020-09-28 13:19 UTC, rrrooommmaaa approved these changes
LGTM, feel free to merge after tests are successful!

2020-09-28 14:28 UTC, ni4 commented
@rrrooommmaaa Thanks, all green - merging this.

2020-09-28 14:28 UTC, merged