set up fuzz issue 24887
rnpgp/rnp pull request #1330
Opened 2020-10-18 12:05 UTC by rrrooommmaaa

There is not an crash, 
just 12 layers (`ctx->layers`) of nested compressed packets and a packet of type 00 (unrecognized) with `indeterminate` length
taking an hour to inflate (via `stream_skip_packet`) to the size of `src->readb` = 779 436 180 361 and finally resulting in an error.
Should we optimize `stream_skip_packet` somehow? for instance, replacing `compressed_src_read` with some function that doesn't invoke `zlib` functions, just skipping data. Would that save us some processing time?

Ping @dewyatt @ni4

2020-10-21 15:41 UTC, ni4 commented
Quite interesting how fuzzer managed to generate such data chunk.

> Should we optimize `stream_skip_packet` somehow? for instance, replacing `compressed_src_read` with some function that doesn't invoke zlib functions, just skipping data. Would that save us some processing time?

We can work around this particular case by replacing:
```
default:
            ret = stream_skip_packet(src);
```
With something like 
```
if ((src.type == PGP_STREAM_COMPRESSED) &&  hdr.indeterminate) {
    // no need to read compressed data while skipping
    return RNP_SUCCESS;
}
```

Updating `stream_skip_packet()` could lead to undesired side effects since at least we would not be able to correctly know number of bytes, read from the source, and some upper layer code may need it.

2020-11-01 19:15 UTC, rrrooommmaaa commented
@ni4 @dewyatt @ronaldtse 
I have re-read the RFC4880 document and it stated that "indeterminate packet length (with old-style length format) means that the length is determined "out of the context" and not "till the end of the stream or whatever".
Looks like the existing code tried to support some features that need not be supported.
In fuzzer data we received packet of tag TRUST with old style indeterminate length and tried to skip it till the end of the stream, but probably we shouldn't have done that. The specs say that TRUST packets are only used in some internal storage files.
I disabled the reading of these indeterminate packets in `stream_read_packet` to immediately return BAD_DATA error and still all tests pass. 
The only data messages that had old-style indeterminate length packets are compressed chunks in
`message-32k-crlf.txt.gpg`, `message.txt.enc-mdc` and `message.txt.enc-no-mdc`  and they are all parsed in `init_packet_params`,
that is: no failures with that `stream_read_packet` change.

2020-11-02 11:26 UTC, ni4 commented
@rrrooommmaaa I don't think that this is a good solution, since it could break working things (like literal indeterminate packet inside of compressed one). And indeterminate packets could definitely appear in old OpenPGP messages, which we must support as well. Why don't you like the solution from the  https://github.com/rnpgp/rnp/pull/1330#issuecomment-713668471 ? It could be improved by adding some sort of function `skip_compressed_contents(pgp_source_t &src)`, which would just read everything from upper layer (probably, calling `skip_compressed_contents()` recursively).

2020-11-02 22:19 UTC, antonsviridenko commented
I need to read some docs about fuzzers first, to make some meaningful review here :)

2020-11-06 13:44 UTC, rrrooommmaaa commented
> @rrrooommmaaa I don't think that this is a good solution, since it could break working things (like literal indeterminate packet inside of compressed one). And indeterminate packets could definitely appear in old OpenPGP messages, which we must support as well. Why don't you like the solution from the [#1330 (comment)](https://github.com/rnpgp/rnp/pull/1330#issuecomment-713668471) ? It could be improved by adding some sort of function `skip_compressed_contents(pgp_source_t &src)`, which would just read everything from upper layer (probably, calling `skip_compressed_contents()` recursively).

That fix didn't help, it was still uncompressing the upper-level stream for hours. There is probably nothing bad about it, but the fuzzer won't get off our backs, though the situation is normal --ZLib slowly decompresses to some hundreds G in small chunks. Still, the input data seems dodgy with regard to TRUST packet with old-styleindeterminate length (TRUST packet is dodgy itself -- the specs say it is only used in some internal files). We can, of course raise error on TRUST packets with indeterminate sizes only, but my point is -- there are two paths where packet length parsing can occur.
if we go via `init_compressed_src` or `init_literal_src`, we go to `init_packet_params()`
```
    } else if (stream_intedeterminate_pkt_len(param->readsrc)) {
        param->indeterminate = true;
        src_skip(param->readsrc, 1);
    } else {
```
and there it is handled correctly.
While the other path is via `stream_read_packet` where I inserted this code:
```
    if (stream_old_indeterminate_pkt_len(src)) {
        return RNP_ERROR_BAD_FORMAT;
    }
```
I'm not entirely sure but we probably don't get there with compressed or literal or encrypted packet?
This looks like a chance to simplify the logic greatly and avoid these dodgy fuzzer's packets along with it.
I'm not entirely sure but probably

2020-11-06 13:45 UTC, rrrooommmaaa commented
Can we get hold of some of these old OpenPGP messages somehow?

2020-11-06 13:59 UTC, rrrooommmaaa commented
> I need to read some docs about fuzzers first, to make some meaningful review here :)

We have several fuzzer targets that accept a single block of data as input and do something about it.
The main idea that the program doesn't crash and finish within reasonable time.
This particular issue is about  `src/fuzzing/dump.c` 
It dumps this chunk to null output `rnp_dump_packets_to_output(input, output, RNP_DUMP_RAW);`
Fuzzer supplied us the data input that makes the program hang (or to be exact it completes within some 3 hours)
So we're examining it. 
We're added this input as a file `src/tests/data/test_fuzz_dump/clusterfuzz-testcase-minimized-fuzz_dump-5757362284265472` to our project and wired a unit test to avoid regression in future. 
Note that `rnp_dump_packets_to_output` returning error code isn't considered a failure. It just shouldn't crash or hang.
And looks like this issue isn't actually a real issue because it "hangs" due to slow unzipping of some garbage data.

2020-11-06 14:15 UTC, antonsviridenko commented
ok thank you for explanations

2020-11-07 18:00 UTC, ni4 commented
@antonsviridenko You may read more about oss-fuzz here: https://google.github.io/oss-fuzz/ . Basically, google's servers continuously run our fuzzers, modifying the input randomly, in attempt to detect byte combination which would lead to failure (crash, hang, out of memory).

2020-11-07 19:27 UTC, ni4 commented
@rrrooommmaaa 
> Can we get hold of some of these old OpenPGP messages somehow?

Probably those may be generated with older versions og PGP 2.x, or GnuPG, but I'm not sure. The thing is that them just may happen at some point in time.

Regarding the compressed packets: what if make things simpler and just limit read bytes to some amount (say, 1Gb) in `stream_read_packet_indeterminate()` ?

2020-11-08 10:17 UTC, rrrooommmaaa commented
> @rrrooommmaaa
> 
> > Can we get hold of some of these old OpenPGP messages somehow?
> 
> Probably those may be generated with older versions og PGP 2.x, or GnuPG, but I'm not sure. The thing is that them just may happen at some point in time.
> 
> Regarding the compressed packets: what if make things simpler and just limit read bytes to some amount (say, 1Gb) in `stream_read_packet_indeterminate()` ?

Would this mean that we're forbidding to sign/encrypt messages longer than 1Gb?
Well, let's just start with error generation on certain packet types with old-style indeterminate lengths?
I'd create a constant list with TRUST packet there and restore original behaviour for other tags?

2020-11-09 10:04 UTC, ni4 commented
> Would this mean that we're forbidding to sign/encrypt messages longer than 1Gb?
Well, let's just start with error generation on certain packet types with old-style indeterminate lengths?
I'd create a constant list with TRUST packet there and restore original behaviour for other tags?

Functions `stream_skip_packet()`/`stream_read_packet()` are used only during packet dumping and skipping of erroneous key packets, so processing of encrypted/signed data will work well. And actually packet dumping should fail as less as possible since it is used to check OpenPGP packets, including erroring ones.

2020-11-09 16:53 UTC, rrrooommmaaa commented
@ni4 Maybe we should introduce timeout parameter for dumping? We have some reliable time calculation functions used for s2k, correct?

2020-11-09 16:54 UTC, rrrooommmaaa commented
Anyway, the old version of `read_indeterminate` copied the code that we now have in `dst_write_src`

2020-11-10 09:58 UTC, ni4 commented
> Maybe we should introduce timeout parameter for dumping? We have some reliable time calculation functions used for s2k, correct?

I don't think we should add time-related calculations on this layer. Limiting amount to be used in packet dumping should be good enough.

2020-11-11 11:41 UTC, rrrooommmaaa commented
> Regarding the compressed packets: what if make things simpler and just limit read bytes to some amount (say, 1Gb) in `stream_read_packet_indeterminate()` ?

@ni4 Done as you requested. Does it look good?

2020-11-12 10:00 UTC, ni4 requested changes
Imho it would be enough to just limit the amount read in `stream_read_packet_indeterminate()` (and some tests), no need to introduce changes on stream level/rename already existing functions.

2020-11-12 10:44 UTC, rrrooommmaaa commented on src/librepgp/stream-packet.cpp
> +stream_old_indeterminate_pkt_len(pgp_source_t *src)
@ni4 yes, because `intedeterminate` is a typo

2020-11-12 10:44 UTC, rrrooommmaaa commented on src/librepgp/stream-common.cpp
> +    return (!src->limit || src->limit <= src->readb);
@ni4 I wanted to re-use `dst_write_src` for pumping

2020-11-12 10:45 UTC, rrrooommmaaa commented on src/tests/streams.cpp
> +    dst_close(&dst, false);
Good idea.

2020-11-12 12:57 UTC, ni4 commented on src/librepgp/stream-packet.cpp
> +stream_old_indeterminate_pkt_len(pgp_source_t *src)
@rrrooommmaaa Oh, was mislooking that typo for years. Thanks.

2020-11-12 13:00 UTC, ni4 commented on src/librepgp/stream-common.cpp
> +    return (!src->limit || src->limit <= src->readb);
@rrrooommmaaa But that will not work as `stream_skip_packet()` uses NULL dst when calling `stream_read_packet()`. I think that it is overhead to change and complicate internals of underlying types/functions, potentially changing behavior,  for just single use-case. Especially when we can simply override with 3 lines of code.

2020-11-16 13:10 UTC, rrrooommmaaa commented on src/tests/streams.cpp
> +    dst_close(&dst, false);
@ni4 I added `assert_true(time(NULL) - start <= 1800);` to `test_fuzz_dump`

2020-11-16 13:11 UTC, rrrooommmaaa commented
@ni4 I adjusted the code according to your comments and made `dst_write_src` compatible with dst = NULL.
Is it good enough to merge now?

2020-11-18 10:18 UTC, ni4 approved these changes
LGTM, thanks! Still needs to check what's wrong with MSYS2 and the second review.

2020-11-19 12:19 UTC, ni4 commented
@rrrooommmaaa MSYS2 CI should be fixed with this PR : https://github.com/rnpgp/rnp/pull/1344

2020-11-20 04:16 UTC, ronaldtse commented
@rrrooommmaaa can we rebase this so it includes the fixed #1344 ? Thanks!

2020-11-20 13:49 UTC, rrrooommmaaa commented
> @rrrooommmaaa can we rebase this so it includes the fixed #1344 ? Thanks!

Done. Can we merge it now, @ronaldtse ?

2020-11-20 17:01 UTC, ronaldtse approved these changes
LGTM @rrrooommmaaa , thank you!

2020-11-20 17:01 UTC, merged