Refactor pgp_packet_body_t to be more C++.
rnpgp/rnp pull request #1350
Opened 2020-11-27 16:06 UTC by ni4

This PR refactors pgp_packet_body_t and packet parsing/writing to be more C++, having cleaner code and destructor-based memory freeing.
It will be updated with the code borrowed from PR #1349 via new PRs once merged.

2020-11-28 11:37 UTC, ni4 commented
There are some CI timeout issues, but those seems to be caused by GHA, investigating them.
@rrrooommmaaa Do you have any idea why windows-msvc builds are so slow (3 hours instead of 20-40 minutes)?

2020-11-28 15:19 UTC, rrrooommmaaa requested changes
I suggest some minor corrections

2020-11-29 10:58 UTC, ni4 commented on src/librepgp/stream-packet.h
> +    void write(pgp_dest_t &dst, bool hdr = true) noexcept;
Thanks, fixed.

2020-11-29 10:58 UTC, ni4 commented on src/librepgp/stream-packet.h
> +    /** @brief append chunk of the data to the packet body
Fixed, thanks.

2020-11-29 11:00 UTC, ni4 commented on src/librepgp/stream-packet.cpp
> +    add(desc->OIDhex, desc->OIDhex_len);
Thanks, will update to `add(desc->OIDhex, (uint8_t) desc->OIDhex_len);`. Actually curve description is set internally, and OIDhex_len will not exceed MAX_CURVE_OID_HEX_LEN.

2020-11-29 13:12 UTC, antonsviridenko approved these changes

2020-11-29 17:08 UTC, rrrooommmaaa approved these changes
LGTM now)

2020-11-30 09:51 UTC, ronaldtse commented
It seems that the macOS test is never completing. I've restarted it a few hours ago...?

2020-11-30 09:54 UTC, ni4 commented
> It seems that the macOS test is never completing. I've restarted it a few hours ago...?

Yeah, I also restarted it few times/tried on my fork. Looks like something is wrong with macOS runners, but still let's investigate it first.

2020-11-30 11:43 UTC, ni4 commented
Looks like macOS 11 GHA works much faster - it finished in 20 minutes here: https://github.com/rnpgp/rnp/pull/1353/
Let's wait and see whether 250 minutes timeout will work for 10.15.

2020-11-30 15:58 UTC, ni4 commented
Merging as we have two approvals and passing CI.

2020-11-30 15:59 UTC, merged