Refactor rnp_key_get_default_key() to avoid code duplication.
rnpgp/rnp pull request #1576
Opened 2021-08-05 14:07 UTC by antonsviridenko

closes #1570

2021-08-06 09:39 UTC, ni4 requested changes
LGTM, just some coding style comments.

2021-08-06 09:39 UTC, ni4 commented on src/lib/rnp.cpp
> +                   bool                    require_secret)
What about `bool require_secret = false`, as it is true only in one call?

2021-08-06 09:39 UTC, ni4 commented on src/lib/rnp.cpp
> +    if (keyflag != PGP_KF_ENCRYPT) {
`bool require_secret = keyflag != PGP_KF_ENCRYPT` for less code lines?

2021-08-06 09:39 UTC, ni4 commented on src/lib/rnp.cpp
> +    ret = rnp_locate_key_int(primary_key->ffi, search, default_key, require_secret);
`rnp_result_t ret = rnp_locate_key_int(...)` for less code lines?

2021-08-06 09:39 UTC, ni4 commented on src/lib/rnp.cpp
> +    if (*default_key == NULL && ret == RNP_SUCCESS) {
We are more stick to the `if (!*default_key && !ret)` convention.

2021-08-06 19:43 UTC, antonsviridenko commented
@ni4 done

2021-08-07 11:52 UTC, ni4 approved these changes
LGTM, thanks, @antonsviridenko !

2021-08-08 09:42 UTC, ronaldtse approved these changes
Thanks @ni4 !

2021-08-08 09:43 UTC, merged