CLI: print info about used backend.
rnpgp/rnp pull request #1626
Opened 2021-09-02 10:20 UTC by antonsviridenko

Closes #1594

2021-09-04 08:55 UTC, antonsviridenko commented
Example output:

Botan backend
```
$ rnp --version
rnp 0.15.2+git20210904.b638e0d
All bug reports, praise and chocolate, please, to:
Ribose Inc. <rnpgp@ribose.com>
Backend: Botan
Backend version: 2.18.1
Supported algorithms:
public key algorithm:  RSA, ELGAMAL, DSA, ECDH, ECDSA, EDDSA, SM2
symmetric algorithm:  IDEA, TRIPLEDES, CAST5, BLOWFISH, AES128, AES192, AES256, TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256, SM4
aead algorithm:  None, EAX, OCB
protection mode:  CFB
hash algorithm:  MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224, SHA3-256, SHA3-512, SM3
compression algorithm:  Uncompressed, ZIP, ZLIB, BZip2
elliptic curve:  NIST P-256, NIST P-384, NIST P-521, Ed25519, Curve25519, brainpoolP256r1, brainpoolP384r1, brainpoolP512r1, secp256k1, SM2 P-256
```

OpenSSL backend
```
$ rnp --version
rnp 0.15.2+git20210901.53e87a7
All bug reports, praise and chocolate, please, to:
Ribose Inc. <rnpgp@ribose.com>
Backend: OpenSSL
Backend version: OpenSSL 1.1.1l  24 Aug 2021
Supported algorithms:
public key algorithm:  RSA, ELGAMAL, DSA, ECDH, ECDSA, EDDSA
symmetric algorithm:  IDEA, TRIPLEDES, CAST5, BLOWFISH, AES128, AES192, AES256, CAMELLIA128, CAMELLIA192, CAMELLIA256
aead algorithm:  None
protection mode:  CFB
hash algorithm:  MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224, SHA3-256, SHA3-512
compression algorithm:  Uncompressed, ZIP, ZLIB, BZip2
elliptic curve:  NIST P-256, NIST P-384, NIST P-521, Ed25519, Curve25519, secp256k1
```

2021-09-07 08:31 UTC, ni4 commented
@antonsviridenko 
I would suggest so slightly groom the message, i.e.:
```
All bug reports, praise and chocolate, please, to:
Ribose Inc. <rnpgp@ribose.com>
Backend: Botan 2.18.1
Supported algorithms:
Public key:  RSA, ELGAMAL, DSA, ECDH, ECDSA, EDDSA, SM2
Encryption:  IDEA, TRIPLEDES, CAST5, BLOWFISH, AES128, AES192, AES256, TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256, SM4
AEAD:  None, EAX, OCB
Key protection:  CFB
Hash:  MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224, SHA3-256, SHA3-512, SM3
Compression:  Uncompressed, ZIP, ZLIB, BZip2
Curves:  NIST P-256, NIST P-384, NIST P-521, Ed25519, Curve25519, brainpoolP256r1, brainpoolP384r1, brainpoolP512r1, secp256k1, SM2 P-256
```
I.e. display backend in a single line, remove redundant 'algorithm' words, shorten names, and start from the capital letter.

2021-09-07 08:36 UTC, ni4 requested changes
LGTM overall, except some changes to the output, see the other comment. Also could you please add some cli test, which runs `rnpkeys --version` and checks it against regexp and `botan --version`/`openssl --version`.

2021-09-07 17:32 UTC, antonsviridenko commented
> I.e. display backend in a single line,

yeah, but in case of OpenSSL it will look this "OpenSSL OpenSSL 1.1.1l  24 Aug 2021" because openssl name is duplicated in version string

or rnp_backend_version() for OpenSSL backend should be changed then, to return numeric string only...

2021-09-07 17:38 UTC, ni4 commented
> > I.e. display backend in a single line,
> 
> 
> 
> yeah, but in case of OpenSSL it will look this "OpenSSL OpenSSL 1.1.1l  24 Aug 2021" because openssl name is duplicated in version string
> 
> 
> 
> or rnp_backend_version() for OpenSSL backend should be changed then, to return numeric string only...

Yeah, it would be better to strip all extra info and leave just numeric version + symbol. Maybe define OPENSSL_VERSION_NUMBER could be helpful.

2021-09-12 03:53 UTC, ronaldtse commented
Let's change the praise to a similar message we have on the man pages:
e.g. https://www.rnpgp.org/docs/rnp-1/

And move it to the end? People probably care about the information more.

Makes me wonder if we should actually do it in a more structured manner like this?
```
Version: rnp 0.15.2+git20210901.53e87a7
Backend: Botan 2.18.1
Algorithms supported:
  Public key:
    - RSA
    - ELGAMAL
    - DSA
    - ECDH
    - ECDSA
    - EDDSA
    - SM2
  Encryption:
    - IDEA
    - TRIPLEDES
    - CAST5
    - BLOWFISH
    - AES128
    - AES192
    - AES256
    - TWOFISH
    - CAMELLIA128
    - CAMELLIA192
    - CAMELLIA256
    - SM4
  AEAD:
    - EAX
    - OCB
    - None
  Key protection:
    - CFB
  Hash:           
    - MD5
    - SHA1
    - RIPEMD160
    - SHA256
    - SHA384
    - SHA512
    - SHA224
    - SHA3-256
    - SHA3-512
    - SM3
  Compression:
    - BZip2
    - ZIP
    - ZLIB
    - Uncompressed
  Curves:
    - NIST P-256
    - NIST P-384
    - NIST P-521
    - Ed25519
    - Curve25519
    - brainpoolP256r1
    - brainpoolP384r1
    - brainpoolP512r1
    - secp256k1
    - SM2
    - P-256

Please report security issues at (https://www.rnpgp.org/feedback) and
general bugs at https://github.com/rnpgp/rnp/issues.
```

2021-09-12 14:17 UTC, ni4 commented
> Makes me wonder if we should actually do it in a more structured manner like this?

@ronaldtse Would not that occupy too many lines on terminal? For more convenient machine processing we may add some additional option (like `--json`) which would output that data, yeah, in JSON.

2021-09-12 20:02 UTC, antonsviridenko commented
I agree about too many lines, version output is usually much shorter for the most of the command line programs.

2021-09-22 11:22 UTC, ni4 commented
@antonsviridenko Would you have time to get back to this PR soon, as It blocks #1596 ?

2021-09-23 02:55 UTC, ronaldtse commented
> @ronaldtse Would not that occupy too many lines on terminal? For more convenient machine processing we may add some additional option (like `--json`) which would output that data, yeah, in JSON.

Agree.

2021-09-23 11:56 UTC, antonsviridenko commented
@ni4 working on it...

2021-09-24 23:25 UTC, antonsviridenko commented
@ni4 
> Also could you please add some cli test, which runs rnpkeys --version and checks it against regexp and botan --version/openssl --version.

How am I supposed to do that when cli_tests are not implemented for OpenSSL backend yet? Check for match with openssl OR botan binary version, i.e. run both `botan --version` and `openssl version` and make sure it matches one of them?

2021-09-25 10:26 UTC, ni4 commented
> How am I supposed to do that when cli_tests are not implemented for OpenSSL backend yet? Check for match with openssl OR botan binary version, i.e. run both `botan --version` and `openssl version` and make sure it matches one of them?

@antonsviridenko you may add test to `cli_tests.py` and check it only locally with OpenSSL backend. So CI will currently check the case with botan backend, and then, once cli_tests would be adapted to OpenSSL, second case will be checked as well.

2021-09-25 22:51 UTC, antonsviridenko commented
ok, the botan executable needs to be explicitly installed for tests

2021-10-01 13:30 UTC, ni4 commented
@antonsviridenko as another option for `cli_tests.py` you may use this approach: https://github.com/rnpgp/rnp/pull/1637/files#diff-d48cf126654869e00d95a75d8f665302094a6d6c2af43ac4e9c5e86e055d5786

2021-10-09 19:28 UTC, antonsviridenko commented
Debian 9 Stretch does not have "botan" package in repository, only libbotan :(

2021-10-10 12:39 UTC, ni4 commented
> Debian 9 Stretch does not have "botan" package in repository, only libbotan :(

I think we should not put too much efforts into this single test. I suggest to not run the test if botan executable is not available.

2021-10-11 00:10 UTC, ronaldtse commented
Agree!

2021-10-14 00:11 UTC, antonsviridenko commented
I think that cached version of botan install is used, where botan cli executable is not enabled in configuration...

2021-10-14 01:53 UTC, ronaldtse commented
Then we have to bust the cache. Some documentation somewhere ;-)

2021-10-20 10:29 UTC, ronaldtse commented
@antonsviridenko could you help rebase here? I think the cache will get updated with the rebas3e.

2021-11-01 04:57 UTC, ribose-jeffreylau commented
There's one failure left, in the `msys2` build:  https://github.com/rnpgp/rnp/runs/4045656933?check_suite_focus=true#step:8:647

```console
CMake Error at D:/a/_temp/msys64/mingw64/share/cmake-3.21/Modules/GoogleTestAddTests.cmake:77 (message):
  Error running test executable.

    Path: 'D:/a/rnp/rnp/builds/rnp-build/src/tests/rnp_tests.exe'
    Result: Exit code 0xc0000135

  

    Output:
      

Call Stack (most recent call first):
  D:/a/_temp/msys64/mingw64/share/cmake-3.21/Modules/GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl)


make[2]: *** [src/tests/CMakeFiles/rnp_tests.dir/build.make:1035: src/tests/rnp_tests.exe] Error 1
make[2]: *** Deleting file 'src/tests/rnp_tests.exe'
make[1]: *** [CMakeFiles/Makefile2:1328: src/tests/CMakeFiles/rnp_tests.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

Searching the net for the exit code `0xc0000135` suggests that it may be related to not having .Net framework installed?  It doesn't sound plausible here...  Any idea?

2021-11-01 05:00 UTC, ribose-jeffreylau commented
> Searching the net for the exit code `0xc0000135` suggests that it may be related to not having .Net framework installed? It doesn't sound plausible here... Any idea?

OK, found some links that point to non-.Net-related issues:

- https://stackoverflow.com/questions/60411677/code-exited-1073741515-0xc0000135-a-dependent-dll-was-not-found
- https://stackoverflow.com/questions/65472823/qt-error-exit-code-1073741515-0xc0000135

Perhaps some PATHs have not been set correctly.

2021-11-01 05:10 UTC, ronaldtse commented
Thanks @ribose-jeffreylau for locating the issue.

@maxirmx could you help take a look at the msys2 problem? Thanks!

2021-11-11 03:07 UTC, ronaldtse commented
Rebased to latest master.

2021-11-11 04:00 UTC, ronaldtse commented
windows-msys2 build failing at:

https://github.com/rnpgp/rnp/runs/4173674810?check_suite_focus=true
```
   INFO: Botan 2.18.2 (revision git:a44f1489239e80937ca67564ff103421e5584069) (unreleased undated) build setup is complete
+ make -j2 install
clang++  -pthread -std=c++11 -D_REENTRANT -D_WIN32_WINNT=0x0600 -fno-omit-frame-pointer -fPIC -Wno-error=unknown-pragmas -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor  -Ibuild/include -c src/lib/asn1/alg_id.cpp -o build/obj/lib/asn1_alg_id.o
clang++  -pthread -std=c++11 -D_REENTRANT -D_WIN32_WINNT=0x0600 -fno-omit-frame-pointer -fPIC -Wno-error=unknown-pragmas -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor  -Ibuild/include -c src/lib/asn1/asn1_obj.cpp -o build/obj/lib/asn1_obj.o
clang++clang++: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msvc'
: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msvc'
make: *** [Makefile:91: build/obj/lib/asn1_alg_id.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:94: build/obj/lib/asn1_obj.o] Error 1
```

2021-11-11 05:49 UTC, ronaldtse commented
Only the 2 windows-msys2 builds failing, they are unable to compile Botan due to `unsupported option '-fPIC'`. 

@maxirmx would you be able to help us with this? Thank you!

2021-11-11 09:15 UTC, maxirmx commented
https://discourse.cmake.org/t/windows-clang-platform-adds-fpic-for-shared-dlls/1784

Would you like me to do it  ?  If so shall I change  antonsviridenko-1594-print-backend-info branch   or create a new one ?

2021-11-11 09:26 UTC, ribose-jeffreylau commented
@maxirmx Would be great if work can continue here.

2021-11-11 10:38 UTC, ronaldtse commented
Now `windows-msys2` is failing in Botan with clang:

```
2021-11-11T10:20:38.8607656Z clang++  -pthread -std=c++11 -D_REENTRANT -D_WIN32_WINNT=0x0600 -fno-omit-frame-pointer -Wno-error=unknown-pragmas -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor  -Ibuild/include -c src/lib/asn1/asn1_obj.cpp -o build/obj/lib/asn1_obj.o
2021-11-11T10:20:40.1816313Z In file included from In file included from src/lib/asn1/alg_id.cpp:8:
2021-11-11T10:20:40.1818081Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.1832783Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.1834160Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.1835170Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:11:
2021-11-11T10:20:40.1836372Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\exception:12:
2021-11-11T10:20:40.1837603Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits:12:
2021-11-11T10:20:40.1839340Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xstddef:283:22src/lib/asn1/asn1_obj.cpp: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
2021-11-11T10:20:40.1840509Z :8:
2021-11-11T10:20:40.1841187Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.1841874Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.1842577Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.1843445Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:11:
2021-11-11T10:20:40.1844914Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\exception:12:
2021-11-11T10:20:40.1846129Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits:12:
2021-11-11T10:20:40.1847512Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xstddef:283:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
2021-11-11T10:20:40.1848867Z _NODISCARD constexpr auto _Unfancy(_Ptrty _Ptr) noexcept { // converts from a fancy pointer to a plain pointer
2021-11-11T10:20:40.1849521Z                      ^
2021-11-11T10:20:40.1850545Z _NODISCARD constexpr auto _Unfancy(_Ptrty _Ptr) noexcept { // converts from a fancy pointer to a plain pointer
2021-11-11T10:20:40.1851708Z                      ^
2021-11-11T10:20:40.5808523Z In file included from In file included from src/lib/asn1/alg_id.cpp:8:
2021-11-11T10:20:40.5814068Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.5815444Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.5818015Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.5819097Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:15:
2021-11-11T10:20:40.5821587Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xmemory:13src/lib/asn1/asn1_obj.cpp:
2021-11-11T10:20:40.5823314Z :C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\limits:1023:5: error: statement not allowed in constexpr function
2021-11-11T10:20:40.5824236Z     do {
2021-11-11T10:20:40.5824628Z     ^
2021-11-11T10:20:40.5825005Z 8:
2021-11-11T10:20:40.5825532Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.5826594Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.5827307Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.5828391Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:15:
2021-11-11T10:20:40.5829519Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xmemory:13:
2021-11-11T10:20:40.5831058Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\limits:1023:5: error: statement not allowed in constexpr function
2021-11-11T10:20:40.5831936Z     do {
2021-11-11T10:20:40.5832299Z     ^
2021-11-11T10:20:40.6229091Z In file included from src/lib/asn1/alg_id.cpp:8:
2021-11-11T10:20:40.6276353Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.6321419Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.6322971Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.6324549Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:15:
2021-11-11T10:20:40.6326376Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xmemory:16:
2021-11-11T10:20:40.6327678Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xutility:15:
2021-11-11T10:20:40.6329294Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\utility:127:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
2021-11-11T10:20:40.6330446Z _NODISCARD constexpr auto&& _Tuple_get(tuple<_Types...>&& _Tuple) noexcept;
2021-11-11T10:20:40.6331042Z                      ^
2021-11-11T10:20:40.6331544Z In file included from src/lib/asn1/asn1_obj.cpp:8:
2021-11-11T10:20:40.6332187Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.6332803Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.6333470Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.6334346Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:15:
2021-11-11T10:20:40.6335430Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xmemory:16:
2021-11-11T10:20:40.6336484Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xutility:15:
2021-11-11T10:20:40.6338032Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\utility:127:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
2021-11-11T10:20:40.6339369Z _NODISCARD constexpr auto&& _Tuple_get(tuple<_Types...>&& _Tuple) noexcept;
2021-11-11T10:20:40.6339955Z                      ^
2021-11-11T10:20:40.6358181Z In file included from src/lib/asn1/alg_id.cpp:8:
2021-11-11T10:20:40.6381096Z In file included from build/include\botan/asn1_obj.h:10:
2021-11-11T10:20:40.6382310Z In file included from build/include\botan/secmem.h:11:
2021-11-11T10:20:40.6384212Z In file included from build/include\botan/types.h:17:
2021-11-11T10:20:40.6385286Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory:15:
2021-11-11T10:20:40.6386878Z In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xmemory:16In file included from :
2021-11-11T10:20:40.6387758Z src/lib/asn1/asn1_obj.cpp:8:
2021-11-11T10:20:40.6388836Z C:\Program Files (x86)\Microsoft Visual Studio\2019\E [...]

2021-11-11 11:26 UTC, maxirmx commented
Sure, it fails
Clang build requires include and lib setting and this botan config ignores everything

I will fix it but it will take some time

2021-11-11 22:25 UTC, maxirmx commented
The last commit shall fix msys/clang issue, however there are more there
1. This one: https://github.com/rnpgp/rnp/pull/1626#issuecomment-955931571   --   it is rnp_tests.exe7 cannot find some shared library   --  if it was fixed earlier please explain since the only approach I see is to create GHA environment locally 
2. I believe that the caching won't work for msys/botan   CI script will delete cached verion and rebuild

2021-11-12 00:10 UTC, ronaldtse commented
@maxirmx the error you mentioned was never fixed, it was only hidden after the updated CI scripts. Would you help fix it since you are our Windows expert? Thanks!

2021-11-12 08:13 UTC, maxirmx commented
@ronaldtse 
Is it really a requirement to build botan eve when the same version is available as binary package ?

2021-11-12 08:26 UTC, ronaldtse commented
Certainly not. However, most of the time the latest Botan version differs from the system installable version.

2021-11-12 08:34 UTC, maxirmx commented
CI script says:
"Found Botan2: D:/a/_temp/msys64/mingw64/lib/libbotan-2.a (found suitable version "2.17.3", minimum required is "2.14.0") "
Then it downloads 2.18.2 sources and builds them locally though 2.18.2 is available as pacman binary package

After that it it looks like it compiles against 2.17.3 includes, links against 2.17.3 import library  but LD_LIBRARY_PATH points to 2.18.2     I am not sure that this is a problem but it definetly adds sime uncertaincy

In the environment described above what is the desired behavior:
- keep system installed 2.17.3 
- install 2.18.2 binary package      (== install newest binary package)
- build 2.18.2 locally                      (==  build newest source package)

?

2021-11-12 11:23 UTC, ribose-jeffreylau commented
> The last commit shall fix msys/clang issue, however there are more there
> 
>     1. This one: [CLI: print info about used backend. #1626 (comment)](https://github.com/rnpgp/rnp/pull/1626#issuecomment-955931571)   --   it is rnp_tests.exe cannot find some shared library   --  if it was fixed earlier please explain since the only approach I see is to create GHA environment locally
> 


@maxirmx I'm currently investigating this.  There is one commit that didn't have these problems, as seen in this CI (which failed for a different reason): https://github.com/ribose-jeffreylau/rnp/runs/4044503223?check_suite_focus=true

2021-11-12 16:04 UTC, antonsviridenko commented
> Is it really a requirement to build botan even when the same version is available as binary package ?
@maxirmx if it provides "botan" executable binary, not just libraries, then package can be used too

2021-11-12 16:17 UTC, ronaldtse commented
Agree with @antonsviridenko !

2021-11-12 16:54 UTC, maxirmx commented
I am confused.

In the master branch botan is used as binary package (for msys) and the issue arised  since this branch changed it to source package.

2021-11-12 16:56 UTC, maxirmx commented
https://packages.msys2.org/package/mingw-w64-x86_64-libbotan?repo=mingw64
https://packages.msys2.org/package/mingw-w64-clang-x86_64-libbotan?repo=clang64

2021-11-12 22:35 UTC, maxirmx commented
- Now using botan binary package and not building botan locally.  It resolves the issue with msys build but now one of the tests fails. 
- botan binary is installed either to /mingw64/bin  or to /clang64/bin  depending on CC setting and this folder is added to the path.  If there is an issue with please give me same details please.
- If we want to build botan locally there is a problem with ci/gha/setup-env.inc.sh    The approach implemented in this script does not work for mingw. It may be easier to apply vcpkg rather then fix setup-env.inc.sh

2021-11-13 09:12 UTC, maxirmx commented
Now it shall work for MSYS

@CAMOBAP,  IMHO the change I made to cli_test.py will be required to support MSYS workflow even when you implement vcpkg

2021-11-13 09:14 UTC, CAMOBAP commented
@maxirmx thanks for the note, maybe you can share a specific commit ref, or this about the whole cli_test.py?

2021-11-13 09:46 UTC, maxirmx commented
@CAMOBAP 
Sorry, this is the commit:
https://github.com/rnpgp/rnp/pull/1626/commits/c96bd4264240fcc5a5950e8d037172f47470f40b

2021-11-14 08:45 UTC, ronaldtse approved these changes
Thank you @maxirmx !

2021-11-14 08:46 UTC, merged