[#1836] fail operations on SM{2,3,4} if configured disabled
rnpgp/rnp pull request #1850
Opened 2022-06-08 12:32 UTC by andrey-utkin

This changeset aims to make the codebase conformant to tests' expectations that any SMx operation fails when `ENABLE_SM2=Off`. It also adds CI coverage for this case.

The new CI run fails without the code patches: https://github.com/rnpgp/rnp/runs/6796644858

The new CI run passes with the patches: https://github.com/rnpgp/rnp/runs/6794059647

Bug: https://github.com/rnpgp/rnp/issues/1836

2022-06-09 12:01 UTC, ni4 requested changes
Almost LGTM, just few minor suggestions.

2022-06-09 13:09 UTC, andrey-utkin commented on src/lib/crypto/hash.cpp
> +#if !defined(ENABLE_SM2)
Without this, `test_stream_verify_no_key` still fails.
One alternative to this is

```
--- a/src/lib/crypto/s2k.cpp
+++ b/src/lib/crypto/s2k.cpp
@@ -86,6 +86,13 @@ pgp_s2k_iterated(pgp_hash_alg_t alg,
                  const uint8_t *salt,
                  size_t         iterations)
 {
+ #if !defined(ENABLE_SM2)
+     if (alg == PGP_HASH_SM3) {
+         RNP_LOG("SM3 hash is not available.");
+         return RNP_ERROR_NOT_IMPLEMENTED;
+     }
+ #endif

```

but I thought it gets a bit too deep into cryptography code and may be just one of too many places to patch.

2022-06-12 10:19 UTC, ni4 commented on src/lib/crypto/hash.cpp
> +#if !defined(ENABLE_SM2)
@andrey-utkin Should not we remove these lines now, as `backend_name()` returns NULL without `ENABLE_SM2`?

2022-06-21 17:53 UTC, andrey-utkin commented on src/lib/crypto/hash.cpp
> +#if !defined(ENABLE_SM2)
Indeed. Dropped. Please re-review.

2022-06-22 00:27 UTC, ronaldtse approved these changes

2022-06-22 13:53 UTC, ni4 approved these changes
LGTM, thanks!

2022-06-22 13:54 UTC, merged