Fix tmpdir cleanup
rnpgp/rnp pull request #1866
Opened 2022-06-27 13:23 UTC by andrey-utkin

A lot of temporary directories are always left around after the tests even when all they all pass. There are a few sources of that, and this patchset addresses them all.

2022-06-28 13:26 UTC, ni4 commented
@andrey-utkin Could you please add check whether run is made under the GHA, so only local runs would be cleaned up automatically? (this should be helpful: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables )

Basically, current centos8 failure is something because of what we should not cleanup CI automatically, and upload artifacts once #1430 is implemented.

2022-06-28 13:26 UTC, ni4 requested changes
Please see a separate comment.

2022-06-28 17:50 UTC, andrey-utkin commented
For now I've added a way to preserve the tempdirs by setting an env var `KEEPTEMP`.

I'd rather make GHA workflows declare explicitly that they want this, by setting that env var, because this simple concept will likely outlive the distinction between GHA and local runs.

We can add this setting in `.github/workflows/*.yml` right now, basically reverting to the previous behaviour in GHA. But I imagine if we start writing actual artifact retention logic, we'd handle it from the context of a failed assertion, which should have the knowledge of what the workdir is, and before the workdir is removed, so the setting is not necessary.

2022-07-04 08:18 UTC, ni4 commented
> For now I've added a way to preserve the tempdirs by setting an env var `KEEPTEMP`.
> 
> I'd rather make GHA workflows declare explicitly that they want this, by setting that env var, because this simple concept will likely outlive the distinction between GHA and local runs.

I doubt that it would be the heaviest problem once migrating away from GHA :-) But, okay, let's use this approach, but it would be better to rename variable to something starting with `RNP_`, like. `RNP_KEEP_TEMP` or so on.

2022-11-22 03:39 UTC, antonsviridenko approved these changes

2022-11-22 15:15 UTC, ni4 commented
@ronaldtse Thanks for bringing this up, somehow missed this. Should be related to test file leftovers...

2022-11-22 15:22 UTC, antonsviridenko commented
yeah, probably some issue introduced by this PR...

2022-11-22 18:14 UTC, ni4 commented
Seems to hang on `SHFileOperationA` call, continuing with debugging...

2022-11-25 16:39 UTC, ni4 commented
@ronaldtse Now it should be good to go. Issue should be in some hanging GUI, displayed during the `SHFileOperationA()`, maybe some readonly file or similar.

2022-11-25 18:40 UTC, ronaldtse commented
Thank you @ni4 ! This is perfect, merging.

2022-11-25 18:40 UTC, merged