Add key edit subcommand --set-expire.
rnpgp/rnp pull request #1978
Opened 2023-01-28 17:41 UTC by antonsviridenko

Closes #1132

2023-01-31 00:42 UTC, ronaldtse approved these changes
Thank you @antonsviridenko !

2023-01-31 11:46 UTC, ni4 requested changes
LGTM, just few minor comments to address/discuss.

2023-01-31 11:46 UTC, ni4 commented on src/rnpkeys/rnpkeys.1.adoc
> +Setting argument to 0 removes key expiration.
For me seems more natural here something like '0 value means that key would never expire (which is not recommended due to security reasons)'.

2023-01-31 11:46 UTC, ni4 commented on src/tests/cli_tests.py
> +        self.assertRegex(err, r'Failed to set key expiration.')
I would recommend to extend test cases with the following checks:
- make sure that expiration didn't change via `--list-packets`
- make sure that expiration is set to exactly same value which was passed via the `--list-packets`.

2023-02-05 09:45 UTC, ni4 approved these changes
LGTM, thanks!

2023-02-05 09:46 UTC, merged