Release v0.16.3
rnpgp/rnp pull request #2048
Opened 2023-04-12 08:21 UTC by ni4

2023-04-12 08:57 UTC, ribose-jeffreylau requested changes

2023-04-12 08:57 UTC, ribose-jeffreylau commented on CHANGELOG.md
> +* Fix for CVE-2023-29479 : possible hang on malformed input.
The following might be more aligned with previous entries regarding fixed CVE:

```diff
-* Fix for CVE-2023-29479 : possible hang on malformed input.
-* Fix for CVE-2023-29480 : in some cases secret keys remain unlocked after use.
+* Fixed issue with possible hang on malformed inputs (CVE-2023-29479).
+* Fixed issue where in some cases, secret keys remain unlocked after use (CVE-2023-29480).
```

2023-04-12 09:29 UTC, ronaldtse approved these changes
Feel free to merge when @ribose-jeffreylau approves. Thanks!

2023-04-12 09:39 UTC, ni4 commented
> Feel free to merge when @ribose-jeffreylau approves. Thanks!

Should we care about the CI failures here? Those must be caused by updated GitHub environment/runners. Locating and picking related commits from the main to the release branch will be quite messy.

2023-04-12 09:40 UTC, ronaldtse commented
Yes we need to fix the CI issues.

2023-04-12 09:56 UTC, ribose-jeffreylau approved these changes

2023-04-13 00:27 UTC, ronaldtse commented
Thank you @ni4 ! Merging now.

2023-04-13 00:27 UTC, merged