Update tests to match SHA1 cutoff date for key signatures.
rnpgp/rnp pull request #2180
Opened 2024-01-19 14:05 UTC by ni4

Fixes #1961

2024-01-20 09:34 UTC, ni4 commented
Not sure why codecov is not happy here.

2024-01-20 10:07 UTC, ronaldtse approved these changes

2024-01-20 11:50 UTC, maxirmx requested changes
With a call to ```encrypt_decrypt``` commented ```test_generate_elgamal_key1024_in_gpg_and_encrypt(self)```  can be removed.

I did not try to understabd the logic, just a formal note.

2024-01-20 11:50 UTC, maxirmx commented on src/tests/cli_tests.py
> -        self._encrypt_decrypt(self.gpg, self.rnp)
It looks like this test is doing nothing now. Am I wrong ?

2024-01-21 16:30 UTC, antonsviridenko approved these changes

2024-01-22 10:46 UTC, maxirmx approved these changes

2024-01-22 12:35 UTC, ni4 commented
Let's merge it as codecov diff report somehow glitched.

2024-01-22 12:35 UTC, merged