Move duplicated parts from symmetric*.cpp to separate file
rnpgp/rnp pull request #2224
Opened 2024-04-28 20:33 UTC by desvxx

2024-04-29 09:24 UTC, ni4 requested changes
It would be also good to move common code of pgp_cipher_cfb_encrypt/pgp_cipher_cfb_decrypt, introducing inline function `pgp_cipher_encrypt_block()` with backend-based implementation.

2024-05-01 19:10 UTC, ni4 approved these changes
LGTM, thanks!

2024-05-02 07:31 UTC, ronaldtse approved these changes

2024-05-02 07:33 UTC, ronaldtse commented
Thank you @desvxx !

2024-05-02 07:33 UTC, merged