Add security override for sha1
rnpgp/rnp pull request #2244
Opened 2024-06-09 00:23 UTC by desvxx

fixes #2181

2024-06-24 09:26 UTC, ni4 commented
@desvxx Could you please rebase this on main, as PR with CI fixes is already merged? Thanks!

2024-07-21 12:30 UTC, ni4 requested changes
Overall LGTM, just few minor updates.

2024-07-21 12:30 UTC, ni4 commented on src/tests/cli_tests.py
> +        self.assertRegex(out, r'(?s)^.*pub.*2024-06-03.*sub.*2024-06-03.*$')
Could you please add NotRegex with INVALID check here?

2024-07-21 12:30 UTC, ni4 commented on src/rnpkeys/rnpkeys.cpp
> +  {"allow-sha1-key-sigs", no_argument, NULL, OPT_ALLOW_SHA1},
Could you please add a new option to the man files as well?

2024-09-06 09:00 UTC, ni4 approved these changes
LGTM, thanks!

2024-09-17 16:04 UTC, maxirmx approved these changes
LGTM

2024-09-17 18:42 UTC, merged