Allow zero-length input in rnp_input_from_memory()
rnpgp/rnp pull request #2246
Opened 2024-06-18 21:02 UTC by desvxx

fixes #2173

2024-06-19 12:11 UTC, ni4 requested changes
Please see the comments.

2024-06-19 12:11 UTC, ni4 commented on src/lib/rnp.cpp
>      if (!input || !buf) {
Please also allow to work with NULL input buffer and zero input size, and add the corresponding test.

2024-06-19 12:11 UTC, ni4 commented on src/tests/ffi-enc.cpp
> +    assert_rnp_success(rnp_input_from_memory(&input, (const uint8_t *) plaintext, 0, false));
Please also make sure that encrypting/signing of zero-size input works as well.

2024-06-29 09:58 UTC, ni4 requested changes
Please see the review comments.

2024-06-29 09:58 UTC, ni4 commented on src/lib/rnp.cpp
> +    if (!input || (!buf && buf_len > 0)) {
It would be logical to replicate behaviour of `init_mem_src()` here, which allows null buffer for the zero-size input.

2024-06-29 09:58 UTC, ni4 commented on src/tests/ffi-enc.cpp
> +TEST_P(ffi_encrypt_tests, test_ffi_encrypt_set_cipher)
Could you please create a new test case instead of heavily modifying this one?

2024-06-29 09:58 UTC, ni4 commented on src/tests/ffi-enc.cpp
> +    if (plaintext == NULL) { // Corner case
We prefer `if (!plaintext)` notation in such cases.

2024-06-29 09:58 UTC, ni4 commented on src/tests/ffi-enc.cpp
> +    assert_rnp_success(rnp_input_from_memory(&input, (const uint8_t *) plaintext, 0, false));
Will not this interfer with the previous code line as plaintext is null?

2024-09-08 12:52 UTC, ni4 approved these changes
LGTM, thanks!

2024-09-08 16:21 UTC, maxirmx approved these changes
OK

2024-09-16 21:04 UTC, merged