Remove path prefix in RNP_LOG
rnpgp/rnp pull request #2297
Opened 2024-12-05 20:55 UTC by desvxx

fixes #2146

2024-12-10 12:25 UTC, maxirmx approved these changes
This is based on the assumption that compiler sets __FILE__ to the file name from the command line.

I am not sure if it works for MSVC

2024-12-11 00:30 UTC, desvxx commented
> This is based on the assumption that compiler sets **FILE** to the file name from the command line.
> 
> I am not sure if it works for MSVC

https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

Indeed, looks like we need /FC option for msvc.

2024-12-27 17:28 UTC, ni4 requested changes
Could you please add some line to cli_tests.py, which makes sure that prefix is not included. This would work for any output made with RNP_LOG, like `self.assertRegex(err, r'(?s)^.*Warning: missing or malformed CRC line.*')`.
Also please rebase so all tests are run (macOS runner was renewed).

2025-01-06 11:20 UTC, ni4 approved these changes
LGTM, thanks!

2025-01-06 11:20 UTC, merged